### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [Zube41/Firehose1#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by Zube41** [comment]
I added "<meta name="viewport" content="width=device-width">" under the <head> section, is that correct?

Also when you changes to the next quote there seems to be a stutter or something that it skips from one to the next one really fast. Did you notice that? Any idea how to fix that?

Thanks

**Comment by BillyMassey** [comment]
You got it Dan! Good job 👍 

As for the 'flickering' -this is actually normal and you didn’t do anything wrong.  We’ve discussed this peculiarity in this forum question here:

http://www.thefirehoseproject.com/comments/13453
